# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6d6924ea8c425f963b19484db173e21eac5f15deb7fcefc9f71cf2d4c73c2844325d19244463a3a8bfb95d5c7db15b461d8bccb7d7ab9fd319caa19988f564a

test:
  secret_key_base: 3fa96f4529e77e98dd4e65aceb7c65cd1a5299a10b0a33035f2751298aafe89adf1de240e0236bfa2d655ff8b015d2f63f08732c593ec081c49bcd8cdac04601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
